WITH R1 AS (
SELECT TOP 200 *
FROM DB_DATALAB_DAF.ML_ANOMALY_SUBSET_CARD_FILTER_2 T1
ORDER BY T1.avg_steps_percent DESC
)
SELECT T2.*, R1.somme_bool
FROM DB_DATALAB_DAF.ML_ANOMALY_SUBSET_NORM T2
INNER JOIN R1
ON  Coalesce(R1.END_SALES_CONTEXT_SALES_CH, '_join') = Coalesce(T2.END_SALES_CONTEXT_SALES_CH, '_join')
AND Coalesce(R1.CONCAT_TYPE_ORDER, '_join') = Coalesce(T2.CONCAT_TYPE_ORDER, '_join')
AND Coalesce(R1.DEPARTEMENT, '_join') = Coalesce(T2.DEPARTEMENT, '_join')
AND Coalesce(R1.LOGISTICS_DELIVERY_MODE, '_join') = Coalesce(T2.LOGISTICS_DELIVERY_MODE, '_join')
AND Coalesce(R1.DEVICE_BRAND_LABEL, '_join') = Coalesce(T2.DEVICE_BRAND_LABEL, '_join')
AND Coalesce(R1.DEPARTEMENT_LIVRAISON, '_join') = Coalesce(T2.DEPARTEMENT_LIVRAISON, '_join')
WHERE T2.RECORDED_DATE BETWEEN DATE_MIN AND DATE_MIN